import Head from 'next/head'
import Image from 'next/image'
import axios from "axios"


// import custom components
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import Home from "../components/Home"

export default function Index({data}) {
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Home data={data}/>
      <Footer/>
    </>
  )
}


export async function getStaticProps() {

  const resData = await axios.get(`${process.env.STRAPI_URL}/api/blogs`)
  const data = resData.data.data

  return {
    props: {data},
  }
}